# Generated by Django 5.2.9 on 2025-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examslot',
            name='time',
        ),
        migrations.AddField(
            model_name='examslot',
            name='time_range',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
