# Generated by Django 5.2.9 on 2025-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_remove_examslot_time_examslot_time_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='floor',
            new_name='columns',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cols',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='rows',
            field=models.IntegerField(),
        ),
    ]
